name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_SDK_VERSION = "6.0"
  DOCKERFILE = "./Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Add custom package source
        run: dotnet nuget add source https://nuget.pkg.github.com/DamianHoogsteder/index.json --username DamianHoogsteder --password ${{ secrets.ACCESS_SECRET }} --store-password-in-clear-text --name github 
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --configuration Release
        
  docker_build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-image -f ${{ env.DOCKERFILE }} .
      - name: Push Docker image
        run: docker push my-image
