name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Add custom package source
        run: dotnet nuget add source https://nuget.pkg.github.com/DamianHoogsteder/index.json --username DamianHoogsteder --password ${{ secrets.ACCESS_SECRET }} --store-password-in-clear-text --name github 
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Add custom package source
        run: dotnet nuget add source https://nuget.pkg.github.com/DamianHoogsteder/index.json --username DamianHoogsteder --password ${{ secrets.ACCESS_SECRET }} --store-password-in-clear-text --name github 
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --configuration Release

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create nuget.config
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > nuget.config
          echo '<configuration>' >> nuget.config
          echo '  <packageSources>' >> nuget.config
          echo '    <add key="public" value="https://api.nuget.org/v3/index.json" />' >> nuget.config
          echo '    <add key="github" value="https://nuget.pkg.github.com/DamianHoogsteder/index.json"  />' >> nuget.config
          echo '  </packageSources>' >> nuget.config
          echo '  <packageSourceCredentials>' >> nuget.config
          echo '    <github>' >> nuget.config
          echo '      <add key="Username" value="${{ env.NUGET_USERNAME }}" />' >> nuget.config
          echo '      <add key="ClearTextPassword" value="${{ secrets.ACCESS_TOKEN }}" />' >> nuget.config
          echo '    </github>' >> nuget.config
          echo '  </packageSourceCredentials>' >> nuget.config
          echo '</configuration>' >> nuget.config
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: zephtos/forfeit15:latest
          file: Forfeit15.Patchnotes/Dockerfile
